// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qinshft.Movies.DataAccess;

#nullable disable

namespace Qinshft.Movies.DataAccess.Migrations
{
    [DbContext(typeof(MovieRentDbContext))]
    partial class MovieRentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Qinshift.Movies.DomainModels.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3297),
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
                            Genre = 3,
                            Title = "Inception",
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3329),
                            Description = "Teddy Daniels and Chuck Aule, two US marshals, are sent to an asylum on a remote island in order to investigate the disappearance of a patient, where Teddy uncovers a shocking truth about the place.",
                            Genre = 4,
                            Title = "Shutter Island",
                            Year = 2010
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3332),
                            Description = "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
                            Genre = 5,
                            Title = "The Departed",
                            Year = 2006
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3335),
                            Description = "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive and can survive until a potential rescue.",
                            Genre = 2,
                            Title = "The Martian",
                            Year = 2015
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3337),
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.",
                            Genre = 1,
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3342),
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            Genre = 3,
                            Title = "Interstellar",
                            Year = 2014
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3345),
                            Description = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            Genre = 1,
                            Title = "Gladiator",
                            Year = 2000
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3348),
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Genre = 5,
                            Title = "The Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3350),
                            Description = "The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.",
                            Genre = 1,
                            Title = "Pulp Fiction",
                            Year = 1994
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3354),
                            Description = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
                            Genre = 5,
                            Title = "Fight Club",
                            Year = 1999
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3357),
                            Description = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
                            Genre = 5,
                            Title = "Forrest Gump",
                            Year = 1994
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3360),
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Genre = 3,
                            Title = "The Matrix",
                            Year = 1999
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3362),
                            Description = "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
                            Genre = 3,
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = 2003
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3365),
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            Genre = 4,
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3367),
                            Description = "In German-occupied Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
                            Genre = 5,
                            Title = "Schindler's List",
                            Year = 1993
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3370),
                            Description = "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.",
                            Genre = 1,
                            Title = "Inglourious Basterds",
                            Year = 2009
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3373),
                            Description = "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
                            Genre = 4,
                            Title = "The Silence of the Lambs",
                            Year = 1991
                        },
                        new
                        {
                            Id = 18,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3376),
                            Description = "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
                            Genre = 5,
                            Title = "Saving Private Ryan",
                            Year = 1998
                        },
                        new
                        {
                            Id = 19,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3379),
                            Description = "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
                            Genre = 1,
                            Title = "Braveheart",
                            Year = 1995
                        },
                        new
                        {
                            Id = 20,
                            CreatedOn = new DateTime(2024, 8, 27, 1, 56, 51, 324, DateTimeKind.Local).AddTicks(3382),
                            Description = "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption, and the federal government.",
                            Genre = 5,
                            Title = "The Wolf of Wall Street",
                            Year = 2013
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
